MESSENGER_PLATFORM = "messenger"

WEBHOOK_MODE_SUBSCRIBE = "subscribe"

EVENT_TYPE_MESSAGE = "message"
EVENT_TYPE_QUICK_REPLY = "quick_reply"
EVENT_TYPE_POSTBACK = "postback"
EVENT_TYPE_UNSUPPORTED = "unsupported"

IDENTITY_STATUS_UNLINKED = "unlinked"
IDENTITY_STATUS_LINKED = "linked"
IDENTITY_STATUS_BLOCKED = "blocked"

DEFAULT_UNLINKED_REPLY = "已收到你的訊息。請先完成網站登入與帳號綁定後再提問。"
DEFAULT_UNSUPPORTED_EVENT_REPLY = "目前僅支援文字訊息與按鈕互動。"

ERROR_CODE_MESSENGER_DISABLED = "MESSENGER_DISABLED"
ERROR_CODE_WEBHOOK_VERIFY_FAILED = "WEBHOOK_VERIFY_FAILED"
ERROR_CODE_WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID"
