MESSENGER_PLATFORM = "messenger"

WEBHOOK_MODE_SUBSCRIBE = "subscribe"

EVENT_TYPE_MESSAGE = "message"
EVENT_TYPE_QUICK_REPLY = "quick_reply"
EVENT_TYPE_POSTBACK = "postback"
EVENT_TYPE_UNSUPPORTED = "unsupported"

IDENTITY_STATUS_UNLINKED = "unlinked"
IDENTITY_STATUS_LINKED = "linked"
IDENTITY_STATUS_BLOCKED = "blocked"

DEFAULT_UNLINKED_REPLY = "已收到你的訊息。請先完成網站登入與帳號綁定後再提問。"
DEFAULT_UNSUPPORTED_EVENT_REPLY = "目前僅支援文字訊息與按鈕互動。"
DEFAULT_MESSENGER_ASK_FAILED_REPLY = "目前暫時無法完成提問，請稍後再試。"
DEFAULT_MESSENGER_TOPUP_REPLY = "目前點數不足，請先購點後再提問。"
DEFAULT_MESSENGER_LINK_BUTTON_TITLE = "登入並綁定"
DEFAULT_MESSENGER_TOPUP_BUTTON_TITLE = "前往購點"
DEFAULT_MESSENGER_RESHOW_FOLLOWUPS_BUTTON_TITLE = "購買完成，重新顯示延伸問題"
DEFAULT_FOLLOWUP_PROMPT_TEXT = "你也可以選擇以下延伸問題："
DEFAULT_MESSENGER_INVALID_FOLLOWUP_REPLY = "這個延伸問題目前無法使用，請重新選擇或重新提問。"
DEFAULT_MESSENGER_FOLLOWUP_UNAVAILABLE_REPLY = "這個延伸問題已失效，請重新提問。"
DEFAULT_MESSENGER_FOLLOWUP_FAILED_REPLY = "目前暫時無法完成延伸問題，請稍後再試。"
DEFAULT_MESSENGER_RESHOW_FOLLOWUPS_UNAVAILABLE_REPLY = (
    "目前沒有可重新顯示的延伸問題，請重新提問。"
)
ERROR_CODE_MESSENGER_LINK_TOKEN_INVALID = "MESSENGER_LINK_TOKEN_INVALID"
ERROR_CODE_MESSENGER_IDENTITY_NOT_FOUND = "MESSENGER_IDENTITY_NOT_FOUND"
ERROR_CODE_MESSENGER_IDENTITY_ALREADY_LINKED = "MESSENGER_IDENTITY_ALREADY_LINKED"

ERROR_CODE_MESSENGER_DISABLED = "MESSENGER_DISABLED"
ERROR_CODE_WEBHOOK_VERIFY_FAILED = "WEBHOOK_VERIFY_FAILED"
ERROR_CODE_WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID"
